### 넘파이(numpy)

In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [15]:
num_arr = np.arange(1,21)

In [16]:
num_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
num_arr[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [25]:
np.sum(num_arr)

210

In [26]:
num_arr.sum()

210

In [70]:
new_arr = num_arr.reshape(5, -1)
new_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

* 2차원 배열 = matrix
* 차원 = dimension
* 축 = axis
    
        * scalar, vector, matrix, tensor => array
             0       1       2      >=3

In [48]:
a = np.array([1,2,3])  # 1차원 scalar

In [49]:
b = np.array([[1,2,3], 
          [4,5,6,]]) # 2차원 matrix

In [50]:
c = np.array([[[1,2,3,],
            [4,5,6]],
            
              [[7,8,9],
           [10,11,12]]])
c                             # 3차원 tensor 

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
c.ndim

3

In [52]:
b.ndim

2

In [88]:
n_arr = np.arange(25).reshape(5, -1)
n_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [90]:
n_arr[0, 0]

0

In [91]:
n_arr[-1,-1]

24

In [93]:
n_arr = np.arange(25).reshape(5, -1)[2:, :]
n_arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [95]:
n_arr = np.arange(25).reshape(5, -1)[0:2, :]
n_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [99]:
n_arr = np.arange(25).reshape(5, -1)
n_arr[0: , ::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

In [101]:
n_arr[0::2, ::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

In [112]:
n_arr[:2].reshape(5, -1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [152]:
np.random.seed(42)
random_num = np.random.rand(4, 2, 5)
random_num

array([[[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
        [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258]],

       [[0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
        [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914]],

       [[0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998],
        [0.78517596, 0.19967378, 0.51423444, 0.59241457, 0.04645041]],

       [[0.60754485, 0.17052412, 0.06505159, 0.94888554, 0.96563203],
        [0.80839735, 0.30461377, 0.09767211, 0.68423303, 0.44015249]]])

In [153]:
random_num.shape

(4, 2, 5)

In [154]:
random_num.argmax()

11

In [155]:
random_num.max()

0.9699098521619943

In [158]:
random_num.flatten()[11]

0.9699098521619943

In [164]:
A = np.ones(25, dtype=int)
A[1::2] = 0
A.reshape(5, 5)

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [167]:
A = np.zeros(25, dtype=int)
A[::2] = 1
A.reshape(5, 5)

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [184]:
import numpy as np
A = np.array([0]*25)
A[::2] = 1
A.reshape(5, 5)

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [188]:
A.sum(axis=0)

13

In [196]:
A = np.arange(32).reshape(4,4,2)
A.flatten()[9]

9

In [199]:
A.flatten()[19]

19

In [202]:
import matplotlib.pyplot as plt # 상관관계가 직선에 가까우면 1을 나타낸다.

In [204]:
x1 = np.arange(100)
x2 = x1 + np.random.randint(1, 10, size=(100,))
x3 = x1 + np.random.randint(1, 50, size=(100,))
x4 = np.random.randint(1, 100, size=(100,))

In [214]:
np.corrcoef([x1, x2, x3, x4])

array([[1.        , 0.99600625, 0.89589711, 0.03388571],
       [0.99600625, 1.        , 0.88622648, 0.02218858],
       [0.89589711, 0.88622648, 1.        , 0.1288981 ],
       [0.03388571, 0.02218858, 0.1288981 , 1.        ]])